// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATABASE_URL: string;
	DIRECT_URL: string;
	PASSWORD_GUEST: string;
	EMAIL_GUEST: string;
	IMAGEKIT_PRIVATE_KEY: string;
	NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: string;
	NEXT_PUBLIC_IMAGEKIT_KEY: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	SMTP_PASSWORD: string;
	SMTP_USER: string;
	SMTP_PORT: string;
	SMTP_HOST: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	OPTIMIZE_API_KEY: string;
}
